name: NodeJS with Parcel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Add generated files
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add docs
        git commit -m "Update production files"
        git push origin main
    
    
